name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Updated to v3 for Node.js 20 support

      - name: Set up JDK 11
        uses: actions/setup-java@v3 # Updated to v3 for Node.js 20 support
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v3 # Updated to v3 for Node.js 20 support
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew test