name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Ensure Gradle Wrapper Exists
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "gradlew script is missing. Generating wrapper..."
            gradle wrapper --gradle-version 8.4
          fi

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: sample-app.apk
          path: app/build/outputs/apk/debug/app-debug.apk